package constants

var (
	MAX_DEPLOYMENTS_IN_PARALLEL int = 15

	POLLING_TIMEOUT int = 900 // 15 minutes (15 * 60 = 900 seconds)

	CANNOT_FIND_SERVICE string = "Cannot find service"

	// List of gcloud build statuses
	GCLOUD_BUILD_STATUS_SUCCESS string = "SUCCESS"

	// List of gcloud build in-progress statuses
	GCLOUD_BUILD_STATUS_STATUS_PENDING string = "PENDING"
	GCLOUD_BUILD_STATUS_STATUS_QUEUED  string = "QUEUED"
	GCLOUD_BUILD_STATUS_STATUS_WORKING string = "WORKING"

	// List of gcloud build failed statuses
	GCLOUD_BUILD_STATUS_STATUS_UNKNOWN        string = "STATUS_UNKNOWN"
	GCLOUD_BUILD_STATUS_FAILURE               string = "FAILURE"
	GCLOUD_BUILD_STATUS_STATUS_INTERNAL_ERROR string = "INTERNAL_ERROR"
	GCLOUD_BUILD_STATUS_STATUS_TIMEOUT        string = "TIMEOUT"
	GCLOUD_BUILD_STATUS_STATUS_CANCELED       string = "CANCELED"
	GCLOUD_BUILD_STATUS_STATUS_EXPIRED        string = "EXPIRED"

	GCLOUD_BUILD_FAILED_STATUSES = []string{
		GCLOUD_BUILD_STATUS_STATUS_UNKNOWN,
		GCLOUD_BUILD_STATUS_FAILURE,
		GCLOUD_BUILD_STATUS_STATUS_INTERNAL_ERROR,
		GCLOUD_BUILD_STATUS_STATUS_TIMEOUT,
		GCLOUD_BUILD_STATUS_STATUS_CANCELED,
		GCLOUD_BUILD_STATUS_STATUS_EXPIRED,
	}

	GCLOUD_BUILD_IN_PROGRESS_STATUSES = []string{
		GCLOUD_BUILD_STATUS_STATUS_PENDING,
		GCLOUD_BUILD_STATUS_STATUS_QUEUED,
		GCLOUD_BUILD_STATUS_STATUS_WORKING,
	}
)
